version: '3'
services:
  worker:
    build: .
    ports:
      - "5050:5050"
    depends_on:
      - redis
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
  redis:
    image: "redis:7.0.5"
    ports:
      - "6379:6379"
  flower:
    image: mher/flower
    command: celery flower
    volumes:
      - ./src:/data
    working_dir: /data
    ports:
      - "5555:5555"
    environment:
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      FLOWER_UNAUTHENTICATED_API: True
    depends_on:
      - worker
      - redis